name: Tests Workflow

on:
  push:
    branches:
      - main
      - dev

  pull_request:
    branches:
      - main
      - dev

jobs:
  test_cs107stargazers_package:
    name: Run Test Suites
    runs-on: ubuntu-latest
    steps:
      # Checkout the head of branch
      - name: Check out repository code
        uses: actions/checkout@v3
      # Setup Python environment in the container
      # See: https://github.com/actions/setup-python
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run MetadataExtractor test suite
        run: pytest -vv test_metadata_extractor.py
        working-directory: tests
      - name: Run Augment test suite
        run: pytest -vv test_augment.py
        working-directory: tests
      - name: Run Ml_stargazer test suite
        run: pytest -vv test_ml_stargazer.py
        working-directory: tests

      - name: Run Query test suite
        run: pytest -vv test_query.py
        working-directory: tests

      - name: Run Preprocessing test suite
        run: pytest -vv test_preprocessing.py
        working-directory: tests

      - name: Run Spectrum Alignment test suite
        run: pytest -vv test_spectrumalignment.py
        working-directory: tests
